### ISSUE TITLE
BUG: Batch analysis over multiple subfolders

### ISSUE THREAD

**Issue by mariacozan** [MouseLand/facemap#101]
### Version information:

numpy version: 1.23.5
python version: 3.8.16

### Describe the issue:

Hi! First of all, thank you for creating this, I've been testing it and it is very useful! I want to now do batch processing over videos which are located in different subfolders within one dataset, however when I try to do this, it seems to duplicate the path, as you can see in this screenshot:
![image](https://user-images.githubusercontent.com/83554323/235726034-0eb09626-4cb2-444e-be39-69b49fddeec6.png)
This then leads to an error as expected (see below).

### Error message:

```shell
`Traceback (most recent call last):
  File "C:\Users\maria\anaconda3\envs\facemap2\lib\site-packages\facemap\gui\menus.py", line 15, in <lambda>
    open_folder.triggered.connect(lambda: io.open_folder(parent))
  File "C:\Users\maria\anaconda3\envs\facemap2\lib\site-packages\facemap\gui\io.py", line 54, in open_folder
    load_movies(parent)
  File "C:\Users\maria\anaconda3\envs\facemap2\lib\site-packages\facemap\gui\io.py", line 347, in load_movies
    parent.jump_to_frame()
  File "C:\Users\maria\anaconda3\envs\facemap2\lib\site-packages\facemap\gui\gui.py", line 1047, in jump_to_frame
    self.next_frame()
  File "C:\Users\maria\anaconda3\envs\facemap2\lib\site-packages\facemap\gui\gui.py", line 1068, in next_frame
    self.imgs[i][:, :, :, 2] = im[i]
IndexError: list index out of range`
```

**Comment by Atika-Syeda** [comment]
Hi @mariacozan if there are any videos in the directory then they should be listed as shown in your screenshot. Please scroll to the right using the scrollbar above the 'done' button then select files from the menu which will be highlighted. Once you've selected the files please click done. Hope this helps.
