### ISSUE TITLE
Certificate Verify Failed

### ISSUE THREAD

**Issue by AbyFlores** [MouseLand/facemap#103]
### Describe the issue:

Trying to run FaceMap, but this error appears in my Anaconda Prompt. 

### Provide environment info:

(facemap) C:\Users\LurLab>conda info

     active environment : facemap
    active env location : C:\Apps\anaconda3\envs\facemap
            shell level : 2
       user config file : C:\Users\LurLab\.condarc
 populated config files : C:\Users\LurLab\.condarc
          conda version : 22.9.0
    conda-build version : 3.21.4
         python version : 3.8.8.final.0
       virtual packages : __cuda=11.7=0
                          __win=0=0
                          __archspec=1=x86_64
       base environment : C:\Apps\anaconda3  (writable)
      conda av data dir : C:\Apps\anaconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Apps\anaconda3\pkgs
                          C:\Users\LurLab\.conda\pkgs
                          C:\Users\LurLab\AppData\Local\conda\conda\pkgs
       envs directories : C:\Apps\anaconda3\envs
                          C:\Users\LurLab\.conda\envs
                          C:\Users\LurLab\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/22.9.0 requests/2.25.1 CPython/3.8.8 Windows/10 Windows/10.0.19041
          administrator : False
             netrc file : None
           offline mode : False

### Error message:

```shell
(facemap) C:\Users\LurLab>python -m facemap
numpy version: 1.24.3
python version: 3.8.16
C:\Apps\anaconda3\envs\facemap\lib\site-packages\umap\distances.py:1063: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @numba.jit()
C:\Apps\anaconda3\envs\facemap\lib\site-packages\umap\distances.py:1071: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @numba.jit()
C:\Apps\anaconda3\envs\facemap\lib\site-packages\umap\distances.py:1086: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @numba.jit()
C:\Apps\anaconda3\envs\facemap\lib\site-packages\umap\umap_.py:660: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @numba.jit()
QGridLayoutEngine::addItem: Cell (2, 0) already taken
QGridLayoutEngine::addItem: Cell (3, 0) already taken
Downloading https://www.facemappy.org/models/facemap_model_state.pt to C:\Users\LurLab\.facemap\models\facemap_model_state.pt
Traceback (most recent call last):
  File "C:\Apps\anaconda3\envs\facemap\lib\urllib\request.py", line 1354, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Apps\anaconda3\envs\facemap\lib\http\client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Apps\anaconda3\envs\facemap\lib\http\client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Apps\anaconda3\envs\facemap\lib\http\client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Apps\anaconda3\envs\facemap\lib\http\client.py", line 1011, in _send_output
    self.send(msg)
  File "C:\Apps\anaconda3\envs\facemap\lib\http\client.py", line 951, in send
    self.connect()
  File "C:\Apps\anaconda3\envs\facemap\lib\http\client.py", line 1425, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "C:\Apps\anaconda3\envs\facemap\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Apps\anaconda3\envs\facemap\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Apps\anaconda3\envs\facemap\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Apps\anaconda3\envs\facemap\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Apps\anaconda3\envs\facemap\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Apps\anaconda3\envs\facemap\lib\site-packages\facemap\__main__.py", line 95, in <module>
    gui.run(
  File "C:\Apps\anaconda3\envs\facemap\lib\site-packages\facemap\gui\gui.py", line 3280, in run
    GUI = MainW(
  File "C:\Apps\anaconda3\envs\facemap\lib\site-packages\facemap\gui\gui.py", line 359, in __init__
    self.make_buttons()
  File "C:\Apps\anaconda3\envs\facemap\lib\site-packages\facemap\gui\gui.py", line 492, in make_buttons
    self.update_pose_model_combo_box()
  File "C:\Apps\anaconda3\envs\facemap\lib\site-packages\facemap\gui\gui.py", line 804, in update_pose_model_combo_box
    models.append(model_loader.get_basemodel_state_path())
  File "C:\Apps\anaconda3\envs\facemap\lib\site-packages\facemap\pose\model_loader.py", line 87, in get_basemodel_state_path
    download_url_to_file(MODEL_STATE_URL, cached_state_file)
  File "C:\Apps\anaconda3\envs\facemap\lib\site-packages\facemap\pose\model_loader.py", line 104, in download_url_to_file
    urlretrieve(url, filename)
  File "C:\Apps\anaconda3\envs\facemap\lib\urllib\request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "C:\Apps\anaconda3\envs\facemap\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Apps\anaconda3\envs\facemap\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\Apps\anaconda3\envs\facemap\lib\urllib\request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Apps\anaconda3\envs\facemap\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "C:\Apps\anaconda3\envs\facemap\lib\urllib\request.py", line 1397, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "C:\Apps\anaconda3\envs\facemap\lib\urllib\request.py", line 1357, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1131)>
(facemap) C:\Users\LurLab>pip install certifi --upgrade
Requirement already satisfied: certifi in c:\apps\anaconda3\envs\facemap\lib\site-packages (2022.12.7)
```

**Comment by AbyFlores** [comment]
Small update, same issue but slightly less errors now:

(facemap) C:\Users\LurLab>python -m facemap
numpy version: 1.23.5
python version: 3.8.16
QGridLayoutEngine::addItem: Cell (2, 0) already taken
QGridLayoutEngine::addItem: Cell (3, 0) already taken
Downloading https://www.facemappy.org/models/facemap_model_state.pt to C:\Users\LurLab\.facemap\models\facemap_model_state.pt
Traceback (most recent call last):
  File "C:\Apps\anaconda3\envs\facemap\lib\urllib\request.py", line 1354, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Apps\anaconda3\envs\facemap\lib\http\client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Apps\anaconda3\envs\facemap\lib\http\client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Apps\anaconda3\envs\facemap\lib\http\client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Apps\anaconda3\envs\facemap\lib\http\client.py", line 1011, in _send_output
    self.send(msg)
  File "C:\Apps\anaconda3\envs\facemap\lib\http\client.py", line 951, in send
    self.connect()
  File "C:\Apps\anaconda3\envs\facemap\lib\http\client.py", line 1425, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "C:\Apps\anaconda3\envs\facemap\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Apps\anaconda3\envs\facemap\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Apps\anaconda3\envs\facemap\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Apps\anaconda3\envs\facemap\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Apps\anaconda3\envs\facemap\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Apps\anaconda3\envs\facemap\lib\site-packages\facemap\__main__.py", line 95, in <module>
    gui.run(
  File "C:\Apps\anaconda3\envs\facemap\lib\site-packages\facemap\gui\gui.py", line 3280, in run
    GUI = MainW(
  File "C:\Apps\anaconda3\envs\facemap\lib\site-packages\facemap\gui\gui.py", line 359, in __init__
    self.make_buttons()
  File "C:\Apps\anaconda3\envs\facemap\lib\site-packages\facemap\gui\gui.py", line 492, in make_buttons
    self.update_pose_model_combo_box()
  File "C:\Apps\anaconda3\envs\facemap\lib\site-packages\facemap\gui\gui.py", line 804, in update_pose_model_combo_box
    models.append(model_loader.get_basemodel_state_path())
  File "C:\Apps\anaconda3\envs\facemap\lib\site-packages\facemap\pose\model_loader.py", line 87, in get_basemodel_state_path
    download_url_to_file(MODEL_STATE_URL, cached_state_file)
  File "C:\Apps\anaconda3\envs\facemap\lib\site-packages\facemap\pose\model_loader.py", line 104, in download_url_to_file
    urlretrieve(url, filename)
  File "C:\Apps\anaconda3\envs\facemap\lib\urllib\request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "C:\Apps\anaconda3\envs\facemap\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Apps\anaconda3\envs\facemap\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\Apps\anaconda3\envs\facemap\lib\urllib\request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Apps\anaconda3\envs\facemap\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "C:\Apps\anaconda3\envs\facemap\lib\urllib\request.py", line 1397, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "C:\Apps\anaconda3\envs\facemap\lib\urllib\request.py", line 1357, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1131)>

**Comment by carsen-stringer** [comment]
We have https enabled for facemappy.org, so it looks like an issue with the local environment (see details [here](https://stackoverflow.com/questions/51925384/unable-to-get-local-issuer-certificate-when-using-requests)). Based on this info you can try `pip install –upgrade certifi`

Or manually download the file at https://www.facemappy.org/models/facemap_model_state.pt and place it in the correct folder (see info in your command line output): 
"Downloading https://www.facemappy.org/models/facemap_model_state.pt to C:\Users\LurLab\.facemap\models\facemap_model_state.pt"

@Atika-Syeda can you please add info on how to download the model manually? we have some example for that from the cellpose readme here: https://github.com/MouseLand/cellpose#download-of-pretrained-models

**Comment by Atika-Syeda** [comment]
sounds good. Updated readme with the instructions.
