### ISSUE TITLE
error while trying to analyze motion svd

### ISSUE THREAD

**Issue by nelson-hc** [MouseLand/facemap#104]
Hi,

I got the following error while I try to analyze motion SVD. I tried uninstalling and reinstalling Facemap but it does not help. I am using the Windows system. Please let me know what is the problem, thanks!

```
C:\Users\hchang356\Anaconda3\envs\facemap\lib\site-packages\facemap\roi.py:251: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.
  ellipse = np.zeros((yrange.size, xrange.size), np.bool)
Traceback (most recent call last):
  File "C:\Users\hchang356\Anaconda3\envs\facemap\lib\site-packages\facemap\gui\gui.py", line 440, in <lambda>
    self.addROI.clicked.connect(lambda clicked: self.add_ROI())
  File "C:\Users\hchang356\Anaconda3\envs\facemap\lib\site-packages\facemap\gui\gui.py", line 970, in add_ROI
    self.ROIs[-1].position(self)
  File "C:\Users\hchang356\Anaconda3\envs\facemap\lib\site-packages\facemap\roi.py", line 251, in position
    ellipse = np.zeros((yrange.size, xrange.size), np.bool)
  File "C:\Users\hchang356\Anaconda3\envs\facemap\lib\site-packages\numpy\__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
Traceback (most recent call last):
  File "C:\Users\hchang356\Anaconda3\envs\facemap\lib\site-packages\facemap\gui\gui.py", line 1263, in process_ROIs
    savename = process.run(
  File "C:\Users\hchang356\Anaconda3\envs\facemap\lib\site-packages\facemap\process.py", line 678, in run
    rois = utils.roi_to_dict(parent.ROIs, parent.rROI)
  File "C:\Users\hchang356\Anaconda3\envs\facemap\lib\site-packages\facemap\utils.py", line 624, in roi_to_dict
    "yrange": r.yrange,
AttributeError: 'sROI' object has no attribute 'yrange'
```

**Comment by jonahpearl** [comment]
It's ultimately an issue with numpy, reverting to numpy==1.21 should solve this: `pip install numpy==1.21` from within the facemap conda environment. They said they'll fix it in the next facemap release, same underlying issue as #102

**Comment by Atika-Syeda** [comment]
Hi @nelson-hc please let us know if the problem still persists in the new release.
