### ISSUE TITLE
BUG: IndexError when processing multiple non-simultaneous videos

### ISSUE THREAD

**Issue by inchinn1** [MouseLand/facemap#108]
### Version information:

(facemap) C:\Users\johnstonlab>python -m facemap
numpy version: 1.21.0
python version: 3.8.16
QGridLayoutEngine::addItem: Cell (2, 0) already taken
QGridLayoutEngine::addItem: Cell (3, 0) already taken
** TORCH CUDA version installed and working. **

Version: 0.2.0 (according to the 'about' dialog in the help menu of the gui)

### Describe the issue:

When trying to process multiple videos recorded sequentially, I get non stop index errors for every frame that exceeds the length of the first video. It still seems to be processing the videos but much slower... 

problem seems to be in gui.py around line 1088 (in next_frame self.update_pose()) and line 1545 ( in update_pose self.pose_likelihood[video_id][:, self.cframe]
e.g. 'IndexError: index 4202 is out of bounds for axis 1 with size 4201'

### Error message:

```shell
Traceback (most recent call last):
  File "C:\Users\johnstonlab\anaconda3\envs\facemap\lib\site-packages\facemap\gui\gui.py", line 1088, in next_frame
    self.update_pose()
  File "C:\Users\johnstonlab\anaconda3\envs\facemap\lib\site-packages\facemap\gui\gui.py", line 1545, in update_pose
    self.pose_likelihood[video_id][:, self.cframe]
IndexError: index 16634 is out of bounds for axis 1 with size 4201
Traceback (most recent call last):
  File "C:\Users\johnstonlab\anaconda3\envs\facemap\lib\site-packages\facemap\gui\gui.py", line 1088, in next_frame
    self.update_pose()
  File "C:\Users\johnstonlab\anaconda3\envs\facemap\lib\site-packages\facemap\gui\gui.py", line 1545, in update_pose
    self.pose_likelihood[video_id][:, self.cframe]
IndexError: index 16635 is out of bounds for axis 1 with size 4201
Traceback (most recent call last):
  File "C:\Users\johnstonlab\anaconda3\envs\facemap\lib\site-packages\facemap\gui\gui.py", line 1088, in next_frame
    self.update_pose()
  File "C:\Users\johnstonlab\anaconda3\envs\facemap\lib\site-packages\facemap\gui\gui.py", line 1545, in update_pose
    self.pose_likelihood[video_id][:, self.cframe]
IndexError: index 16636 is out of bounds for axis 1 with size 4201
```

**Comment by Atika-Syeda** [comment]
Hi @inchinn1, the GUI currently only supports either single video processing or multi-view videos when recorded simultaneously which are processed sequentially. If you would like to do batch processing of multiple videos recorded sequentially then I'd suggest running it in a notebook. Please see "Process batch of videos" section [here](https://github.com/MouseLand/facemap/blob/dev/notebooks/process_keypoints.ipynb)
