### ISSUE TITLE
BUG: OverflowError

### ISSUE THREAD

**Issue by dtran1125** [MouseLand/facemap#119]
### Version information:

numpy version: 1.23.3
python version: 3.10.6
Running Facemap GUI w/ pose tracking

### Describe the issue:

Hello! I can use facemap with video less than 2 hours just fine. However, when I process videos that have more than 2 hours of recording time, it gives me the OverflowError. Is there anyway to fix this? I also tried to reduce the resolution of my video and run facemap again after, but the error still exists.

Thanks,
Duy

### Error message:

```shell
Traceback (most recent call last):
  File "/home/duy/facemap-dev/facemap/gui/gui.py", line 1118, in process_batch
    savename = process.run(
  File "/home/duy/facemap-dev/facemap/process.py", line 857, in run
    savename = save(proc, savepath)
  File "/home/duy/facemap-dev/facemap/process.py", line 599, in save
    np.save(savename, proc)
  File "<__array_function__ internals>", line 180, in save
  File "/home/duy/anaconda3/envs/facemap/lib/python3.10/site-packages/numpy/lib/npyio.py", line 502, in save
    format.write_array(fid, arr, allow_pickle=allow_pickle,
  File "/home/duy/anaconda3/envs/facemap/lib/python3.10/site-packages/numpy/lib/format.py", line 678, in write_array
    pickle.dump(array, fp, protocol=3, **pickle_kwargs)
OverflowError: serializing a bytes object larger than 4 GiB requires pickle protocol 4 or higher
```

**Comment by Atika-Syeda** [comment]
Hi @dtran1125 we currently don't have a method for saving data for large videos so you could try trimming/splitting the video. We hope to change the method in the future.
