### ISSUE TITLE
deprecated pixel format used, make sure you did set range correctly

### ISSUE THREAD

**Issue by christinabuetfering** [MouseLand/facemap#12]
Hi Carsen,

Thanks so much for sharing all this amazing code!
I am preparing a lab meeting to show all the wonderful things in MouseLand but I am having trouble with FaceMap.
I am opening FaceMap from an anaconda prompt on a Windows machine and I am loading your video from the data analysis course but I get the following error. 

(mouseland) C:\Users\chris>python -m facemap
C:/Users/chris/Downloads/mouse_face.mp4
deprecated pixel format used, make sure you did set range correctly_

I installed git and pims and went through all the common issue comments you have up but I cannot fix it. The video still loads and I can select ROIs but when I want to process them the error repeats and it crashes eventually (posted below). 

Do you have any idea what is causing the problem? 
Thank you so much!
Christina

_...
deprecated pixel format used, make sure you did set range correctly
 (repeated 197 more times)
deprecated pixel format used, make sure you did set range correctly
Traceback (most recent call last):
  File "C:\Users\chris\Anaconda3\envs\mouseland\lib\site-packages\facemap\gui.py", line 946, in process_ROIs
    savename = process.run(self.filenames, self, savepath=savepath)
  File "C:\Users\chris\Anaconda3\envs\mouseland\lib\site-packages\facemap\process.py", line 496, in run
    avgframe, avgmotion = subsampled_mean(video, cumframes, Ly, Lx, sbin)
  File "C:\Users\chris\Anaconda3\envs\mouseland\lib\site-packages\facemap\process.py", line 98, in subsampled_mean
    get_frames_pims(imall, containers, np.arange(t,t+nt0), cumframes)
  File "C:\Users\chris\Anaconda3\envs\mouseland\lib\site-packages\facemap\process.py", line 23, in get_frames_pims
    imall[ii] = np.array(video[n][ii][cfr[0]-cumframes[n]:cfr[-1]-cumframes[n]+1])[:,:,:,0].transpose((1,2,0))
  File "C:\Users\chris\Anaconda3\envs\mouseland\lib\site-packages\slicerator\__init__.py", line 227, in <genexpr>
    return (self._get(i) for i in self.indices)
  File "C:\Users\chris\Anaconda3\envs\mouseland\lib\site-packages\slicerator\__init__.py", line 207, in _get
    return self._ancestor[key]
  File "C:\Users\chris\Anaconda3\envs\mouseland\lib\site-packages\slicerator\__init__.py", line 188, in __getitem__
    return self._get(indices)
  File "C:\Users\chris\Anaconda3\envs\mouseland\lib\site-packages\pims\base_frames.py", line 148, in __getitem__
    return self.get_frame(key)
  File "C:\Users\chris\Anaconda3\envs\mouseland\lib\site-packages\pims\pyav_reader.py", line 376, in get_frame
    raise AssertionError("Seeking failed to obtain the correct frame.")
AssertionError: Seeking failed to obtain the correct frame._

**Comment by carsen-stringer** [comment]
this does look like a pims issue, you pip installed the git version of pims?
```
pip install git+https://github.com/soft-matter/pims.git
```
another possibility maybe is that the frames in the movie are non integer

are you loading one video of one view? (first button)
