### ISSUE TITLE
BUG: <Enter comprehensive title here>

### ISSUE THREAD

**Issue by phanhuynh** [MouseLand/facemap#144]
### Version information:

facemap version:        1.0.6
platform:               win32
python version:         3.8.18
torch version:          2.1.0+cpu
numpy version:          1.24.4

### Describe the issue:

Hello again,
So after I run the initial keypoints tracking (which produces the h5 file), I spend several hours fine tuning (which produced the refined_data.npy).  It took me longer probably because I'm not using facemap as it was intended, and I'm analyzing an entire mouse body.  
Nonetheless, when I added some more ROIs to do SVD, it stopped working (I don't have the error message anymore).  
Now I'm trying to redo the keypoint predictions with the same video.  To save time, I'd like to use the refined_data.npy file from the previous session but this is when the error below appeared.  Any ideas?        

### Error message:

```shell
Traceback (most recent call last):
  File "C:\Users\huynh\AppData\Local\anaconda3\envs\facemap\lib\site-packages\facemap\gui\gui.py", line 881, in set_frame_changed
    self.jump_to_frame()
  File "C:\Users\huynh\AppData\Local\anaconda3\envs\facemap\lib\site-packages\facemap\gui\gui.py", line 1082, in jump_to_frame
    self.next_frame()
  File "C:\Users\huynh\AppData\Local\anaconda3\envs\facemap\lib\site-packages\facemap\gui\gui.py", line 1113, in next_frame
    self.update_pose()
  File "C:\Users\huynh\AppData\Local\anaconda3\envs\facemap\lib\site-packages\facemap\gui\gui.py", line 1566, in update_pose
    self.pose_likelihood[video_id][:, self.cframe]
IndexError: index 1 is out of bounds for axis 0 with size 1
```

**Comment by Atika-Syeda** [comment]
Hi @phanhuynh please make sure the keypoints file is not loaded when you redo the keypoints prediction as it will lead to an error in loading.
