### ISSUE TITLE
Error installing facemap on Linux: PyQt6 - Preparing metadata (pyproject.toml) did not run successfully.

### ISSUE THREAD

**Issue by MirArt94** [MouseLand/facemap#145]
### Describe the issue:

I am trying to set up facemap on a Linux GPU server but running `python -m pip install facemap[gui]` causes an error. The same error occurs when trying to install facemap using the environment.yml file from the downloaded github repository. 

When running `python -m pip install facemap` I do not get this error, however I am told that a package is missing. Once I install the package, another package is declared missing. The following packages were missing and installed one after the other by `pip install <missing package>`: pyqtgraph, matlplotlib, umap, qtpy, pyqt6.

Trying to install pyqt6 manually I get the same error as before when running `python -m pip install facemap[gui]`. I tried fixing this by making sure that qmake is on `PATH` as suggested here (https://pypi.org/project/PyQt6/) but I still got the same error message.

I freshly installed the latest Anaconda version in my user directory in order to prevent interfering with other users using an older version compatible to their environments. 

Am I missing something trivial or how could this be solved?

### Provide environment info:

     active environment : facemap
    active env location : /home/mirko.articus/anaconda3/envs/facemap
            shell level : 2
       user config file : /home/mirko.articus/.condarc
 populated config files : 
          conda version : 24.3.0
    conda-build version : 24.3.0
         python version : 3.11.7.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=cascadelake
                          __conda=24.3.0=0
                          __cuda=11.2=0
                          __glibc=2.27=0
                          __linux=4.15.0=0
                          __unix=0=0
       base environment : /home/mirko.articus/anaconda3  (writable)
      conda av data dir : /home/mirko.articus/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/mirko.articus/anaconda3/pkgs
                          /home/mirko.articus/.conda/pkgs
       envs directories : /home/mirko.articus/anaconda3/envs
                          /home/mirko.articus/.conda/envs
               platform : linux-64
             user-agent : conda/24.3.0 requests/2.31.0 CPython/3.11.7 Linux/4.15.0-180-generic ubuntu/18.04.6 glibc/2.27 solver/libmamba conda-libmamba-solver/24.1.0 libmambapy/1.5.8 aau/0.4.4 c/. s/. e/.
                UID:GID : 117973:100513
             netrc file : None
           offline mode : False

### Error message:

```shell
#### Error message when running `python -m pip install facemap[gui]` ####

Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  Preparing metadata (pyproject.toml) did not run successfully.
  exit code: 1
  
  [28 lines of output]
  Querying qmake about your Qt installation...
  pyproject.toml: line 7: using '[tool.sip.metadata]' to specify the project metadata is deprecated and will be removed in SIP v7.0.0, use '[project]' instead
  Traceback (most recent call last):
    File "/home/mirko.articus/anaconda3/envs/facemap/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/home/mirko.articus/anaconda3/envs/facemap/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/mirko.articus/anaconda3/envs/facemap/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
      whl_basename = backend.build_wheel(metadata_directory, config_settings)
    File "/tmp/pip-build-env-bqnuu5vi/overlay/lib/python3.8/site-packages/sipbuild/api.py", line 46, in build_wheel
      project = AbstractProject.bootstrap('wheel',
    File "/tmp/pip-build-env-bqnuu5vi/overlay/lib/python3.8/site-packages/sipbuild/abstract_project.py", line 92, in bootstrap
      project.setup(pyproject, tool, tool_description)
    File "/tmp/pip-build-env-bqnuu5vi/overlay/lib/python3.8/site-packages/sipbuild/project.py", line 587, in setup
      self.apply_user_defaults(tool)
    File "project.py", line 66, in apply_user_defaults
      super().apply_user_defaults(tool)
    File "/tmp/pip-build-env-bqnuu5vi/overlay/lib/python3.8/site-packages/pyqtbuild/project.py", line 51, in apply_user_defaults
      super().apply_user_defaults(tool)
    File "/tmp/pip-build-env-bqnuu5vi/overlay/lib/python3.8/site-packages/sipbuild/project.py", line 237, in apply_user_defaults
      self.builder.apply_user_defaults(tool)
    File "/tmp/pip-build-env-bqnuu5vi/overlay/lib/python3.8/site-packages/pyqtbuild/builder.py", line 59, in apply_user_defaults
      self._get_qt_configuration()
    File "/tmp/pip-build-env-bqnuu5vi/overlay/lib/python3.8/site-packages/pyqtbuild/builder.py", line 478, in _get_qt_configuration
      for line in project.read_command_pipe([self.qmake, '-query']):
    File "/tmp/pip-build-env-bqnuu5vi/overlay/lib/python3.8/site-packages/sipbuild/project.py", line 554, in read_command_pipe
      raise UserException(
  sipbuild.exceptions.UserException
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

Encountered error while generating package metadata.

See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

#### Error message when installing from environment.yml file ####

 Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'error'

Pip subprocess error:
  error: subprocess-exited-with-error
  
  Preparing metadata (pyproject.toml) did not run successfully.
  exit code: 1
  
  [28 lines of output]
  Querying qmake about your Qt installation...
  pyproject.toml: line 7: using '[tool.sip.metadata]' to specify the project metadata is deprecated and will be removed in SIP v7.0.0, use '[project]' instead
  Traceback (most recent call last):
    File "/home/mirko.articus/anaconda3/envs/facemap/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/home/mirko.articus/anaconda3/envs/facemap/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/mirko.articus/anaconda3/envs/facemap/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
      whl_basename = backend.build_wheel(metadata_directory, config_settings)
    File "/tmp/pip-build-env-oep4imt1/overlay/lib/python3.8/site-packages/sipbuild/api.py", line 46, in build_wheel
      project = AbstractProject.bootstrap('wheel',
    File "/tmp/pip-build-env-oep4imt1/overlay/lib/python3.8/site-packages/sipbuild/abstract_project.py", line 92, in bootstrap
      project.setup(pyproject, tool, tool_description)
    File "/tmp/pip-build-env-oep4imt1/overlay/lib/python3.8/site-packages/sipbuild/project.py", line 587, in setup
      self.apply_user_defaults(tool)
    File "project.py", line 66, in apply_user_defaults
      super().apply_user_defaults(tool)
    File "/tmp/pip-build-env-oep4imt1/overlay/lib/python3.8/site-packages/pyqtbuild/project.py", line 51, in apply_user_defaults
      super().apply_user_defaults(tool)
    File "/tmp/pip-build-env-oep4imt1/overlay/lib/python3.8/site-packages/sipbuild/project.py", line 237, in apply_user_defaults
      self.builder.apply_user_defaults(tool)
    File "/tmp/pip-build-env-oep4imt1/overlay/lib/python3.8/site-packages/pyqtbuild/builder.py", line 59, in apply_user_defaults
      self._get_qt_configuration()
    File "/tmp/pip-build-env-oep4imt1/overlay/lib/python3.8/site-packages/pyqtbuild/builder.py", line 478, in _get_qt_configuration
      for line in project.read_command_pipe([self.qmake, '-query']):
    File "/tmp/pip-build-env-oep4imt1/overlay/lib/python3.8/site-packages/sipbuild/project.py", line 554, in read_command_pipe
      raise UserException(
  sipbuild.exceptions.UserException
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

Encountered error while generating package metadata.

See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

failed

CondaEnvException: Pip failed
```

**Comment by MirArt94** [comment]
I came to realise that this might rather be a more general issue connected to pyqt (not yet too familiar with python...). Using facemap 1.03 with pyqt5 I was able to set everything up and to start tracking.

Thank you for this great resource!
