### ISSUE TITLE
Opencv not found when running "python -m facemap"

### ISSUE THREAD

**Issue by tvajtay** [MouseLand/facemap#15]
When I try running ```python -m facemap``` I receive the following error.

```
(facemap) C:\Users\tomva\Desktop\facemap-master>python -m facemap
Traceback (most recent call last):
  File "C:\Users\tomva\Anaconda3\envs\facemap\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\tomva\Anaconda3\envs\facemap\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\tomva\Desktop\facemap-master\facemap\__main__.py", line 3, in <module>
    from facemap import gui,process
  File "C:\Users\tomva\Desktop\facemap-master\facemap\gui.py", line 12, in <module>
    from . import process, roi, utils, io, menus, guiparts, online
  File "C:\Users\tomva\Desktop\facemap-master\facemap\menus.py", line 3, in <module>
    from . import guiparts, io, online
  File "C:\Users\tomva\Desktop\facemap-master\facemap\online.py", line 4, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
```

However when I run ```python facemap``` a more basic GUI loads that allows me to set ROI's and process but doesn't show traces.

**Comment by carsen-stringer** [comment]
sorry about this issue, you can install cv2 with 
~~~
pip install opencv_python
~~~

Now run `python -m facemap`

That basic GUI was for online eye tracking :) at some point I'll post the fully integrated online version of facemap

**Comment by tvajtay** [comment]
That works, thanks!
