### ISSUE TITLE
Nueral response prediction error

### ISSUE THREAD

**Issue by shanggao11** [MouseLand/facemap#153]
Hi there!
May I ask a question about the neural response prediction part?
I have a neural response array in firing rate (FRarray)along with camera stamps and neural stamps; both camera stamps(CSarray) and neural stamps(NSarray) are in frames. NSarray.shape==FRarray.shape(if ignore the number of neurons); CSarray.shape match with the input video frames (I input a 5 mins data, but the facemap only read in 4.2 mins data, I tried both the size of 5 and 4.2 mins); It gave me this error when I run the neural response prediction, Please help me about this, thank you very much!:

at non-singleton dimension 1
pose data shape (3, 15, 50531)
xy.shape (50531, 15, 2)
outlier filter shape (50531, 15, 2)
x.shape (50531, 30)
Neural target shape:  (300002, 10)
Keypoints shape:  (50531, 30)
Inputs:  (50531, 30)
Neural:  (300002, 10)
Using lr, n_iter, weight_decay:  0.001 300 0.0001
Ignoring window icon 4534162 exceeds maximum xcb request length 4194303
Ignoring window icon 4534162 exceeds maximum xcb request length 4194303
Traceback (most recent call last):
  File "/home/isocortex/miniconda3/envs/facemap/lib/python3.8/site-packages/facemap/gui/neural_activity_window.py", line 537, in <lambda>
    lambda clicked: self.run_neural_predictions(clicked, dialog)
  File "/home/isocortex/miniconda3/envs/facemap/lib/python3.8/site-packages/facemap/gui/neural_activity_window.py", line 653, in run_neural_predictions
    ) = prediction_utils.get_keypoints_to_neural_varexp(
  File "/home/isocortex/miniconda3/envs/facemap/lib/python3.8/site-packages/facemap/neural_prediction/prediction_utils.py", line 448, in get_keypoints_to_neural_varexp
    ) = model.train_model(
  File "/home/isocortex/miniconda3/envs/facemap/lib/python3.8/site-packages/facemap/neural_prediction/neural_model.py", line 184, in train_model
    loss = ((y_pred - Y_train[i][n].unsqueeze(0)) ** 2).mean()
RuntimeError: The size of tensor a (4503) must match the size of tensor b (22500) at non-singleton dimension 1

**Comment by shanggao11** [comment]
> Thanks for your reply! yes,i am sure that I load the camera and neural stamps.

Thanks for your reply! yes,i am sure that I load the camera and neural stamps.

**Comment by shanggao11** [comment]
> Hi @shanggao11 can you please confirm if you also load the camera and neural stamps when you run the prediction?

Thanks for your reply! yes,i am sure that I load the camera and neural stamps.

**Comment by Atika-Syeda** [comment]
Can you please share facemap and other packages version info please?

**Comment by shanggao11** [comment]
Hi, Thank you for your response, here is the packages in the facemap environment:
name: facemap
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alsa-lib=1.2.7.2=h166bdaf_0
  - attr=2.5.1=h166bdaf_1
  - blosc=1.21.1=h83bc5f7_3
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2022.9.24=ha878542_0
  - dbus=1.13.6=h5008d03_3
  - expat=2.4.9=h27087fc_0
  - fftw=3.3.10=nompi_hf0379b8_105
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.0=hc2a2eb6_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.12.1=hca18f0e_0
  - gettext=0.19.8.1=h27087fc_1009
  - glib=2.74.0=h6239696_0
  - glib-tools=2.74.0=h6239696_0
  - gst-plugins-base=1.20.3=h57caac4_2
  - gstreamer=1.20.3=hd4edc92_2
  - hdbscan=0.8.28=py39hce5d2b2_1
  - hdf5=1.12.2=nompi_h2386368_100
  - icu=70.1=h27087fc_0
  - jack=1.9.18=h8c3723f_1003
  - joblib=1.2.0=pyhd8ed1ab_0
  - jpeg=9e=h166bdaf_2
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.19.3=h3790be6_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - libblas=3.9.0=16_linux64_openblas
  - libcap=2.65=ha37c62d_0
  - libcblas=3.9.0=16_linux64_openblas
  - libclang=14.0.6=default_h2e3cab8_0
  - libclang13=14.0.6=default_h3a83d3e_0
  - libcups=2.3.3=h3e49a29_2
  - libcurl=7.85.0=h7bff187_0
  - libdb=6.2.32=h9c3ff4c_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.10=h9b69904_4
  - libffi=3.4.2=h7f98852_5
  - libflac=1.3.4=h27087fc_0
  - libgcc-ng=12.1.0=h8d9b700_16
  - libgfortran-ng=12.1.0=h69a702a_16
  - libgfortran5=12.1.0=hdcd56e2_16
  - libglib=2.74.0=h7a41b64_0
  - libgomp=12.1.0=h8d9b700_16
  - libiconv=1.17=h166bdaf_0
  - liblapack=3.9.0=16_linux64_openblas
  - libllvm11=11.1.0=he0ac6c6_4
  - libllvm14=14.0.6=he0ac6c6_0
  - libnghttp2=1.47.0=hdcd2b5c_1
  - libnsl=2.0.0=h7f98852_0
  - libogg=1.3.4=h7f98852_1
  - libopenblas=0.3.21=pthreads_h78a6416_3
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.38=h753d276_0
  - libpq=14.5=hd77ab85_0
  - libsndfile=1.0.31=h9c3ff4c_1
  - libsqlite=3.39.4=h753d276_0
  - libssh2=1.10.0=haa6b8db_3
  - libstdcxx-ng=12.1.0=ha89aaad_16
  - libtool=2.4.6=h9c3ff4c_1008
  - libudev1=249=h166bdaf_4
  - libuuid=2.32.1=h7f98852_1000
  - libvorbis=1.3.7=h9c3ff4c_0
  - libxcb=1.13=h7f98852_1004
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.10.2=h4c7fe37_1
  - libzlib=1.2.12=h166bdaf_4
  - llvmlite=0.39.1=py39h7d9a04d_0
  - lz4-c=1.9.3=h9c3ff4c_1
  - lzo=2.10=h516909a_1000
  - mysql-common=8.0.30=haf5c9bc_1
  - mysql-libs=8.0.30=h28c427c_1
  - ncurses=6.3=h27087fc_1
  - nomkl=1.0=h5ca1d4c_0
  - nspr=4.32=h9c3ff4c_1
  - nss=3.78=h2350873_0
  - numba=0.56.2=py39h61ddf18_1
  - numexpr=2.8.3=py39h194a79d_100
  - numpy=1.23.3=py39hba7629e_0
  - openssl=1.1.1q=h166bdaf_0
  - packaging=21.3=pyhd8ed1ab_0
  - pcre2=10.37=hc3806b6_1
  - pip=22.2.2=pyhd8ed1ab_0
  - ply=3.11=py_1
  - portaudio=19.6.0=h8e90077_6
  - pthread-stubs=0.4=h36c2ea0_1001
  - pulseaudio=14.0=h0868958_9
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyqt=5.15.7=py39h18e9c17_0
  - pyqt5-sip=12.11.0=py39h5a03fae_0
  - pytables=3.7.0=py39hee6f8ba_2
  - python=3.9.13=h9a8a25e_0_cpython
  - python_abi=3.9=2_cp39
  - qt-main=5.15.6=hc525480_0
  - readline=8.1.2=h0f457ee_0
  - scikit-learn=1.1.2=py39he5e8d7e_0
  - scipy=1.9.1=py39h8ba3f38_0
  - setuptools=65.4.1=pyhd8ed1ab_0
  - sip=6.6.2=py39h5a03fae_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.9=hbd366e4_1
  - sqlite=3.39.4=h4ff8645_0
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - tk=8.6.12=h27826a3_0
  - toml=0.10.2=pyhd8ed1ab_0
  - tzdata=2022d=h191b570_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - xcb-util=0.4.0=h166bdaf_0
  - xcb-util-image=0.4.0=h166bdaf_0
  - xcb-util-keysyms=0.4.0=h166bdaf_0
  - xcb-util-renderutil=0.3.9=h166bdaf_0
  - xcb-util-wm=0.4.1=h166bdaf_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xz=5.2.6=h166bdaf_0
  - zstd=1.5.2=h6239696_4
  - pip:
    - certifi==2022.9.24
    - charset-normalizer==2.1.1
    - contourpy==1.0.5
    - cycler==0.11.0
    - facemap==0.2.0
    - fonttools==4.37.4
    - idna==3.4
    - kiwisolver==1.4.4
    - matplotlib==3.6.1
    - natsort==8.2.0
    - opencv-python-headless==4.6.0.66
    - pandas==1.5.0
    - pillow==9.2.0
    - pynndescent==0.5.7
    - pyqtgraph==0.11.0rc0
    - python-dateutil==2.8.2
    - pytz==2022.4
    - requests==2.28.1
    - torch==1.11.0
    - torchvision==0.12.0
    - tqdm==4.64.1
    - typing-extensions==4.4.0
    - umap-learn==0.5.3
    - urllib3==1.26.12
