### ISSUE TITLE
Error in Save *.mat file option in python GUI

### ISSUE THREAD

**Issue by LiuDaveLiu** [MouseLand/facemap#18]
Error during saving the motion SVD.

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\facemap\gui.py", line 956, in
process_ROIs
    savename = process.run(self.filenames, self, savepath=savepath)
  File "C:\ProgramData\Anaconda3\lib\site-packages\facemap\process.py", line 577
, in run
    savename = save(proc, savepath)
  File "C:\ProgramData\Anaconda3\lib\site-packages\facemap\process.py", line 406
, in save
    io.savemat(savenamemat, {'proc': proc})
  File "C:\ProgramData\Anaconda3\lib\site-packages\scipy\io\matlab\mio.py", line
279, in savemat
    MW.put_variables(mdict)
  File "C:\ProgramData\Anaconda3\lib\site-packages\scipy\io\matlab\mio5.py", lin
e 849, in put_variables
    self._matrix_writer.write_top(var, asbytes(name), is_global)
  File "C:\ProgramData\Anaconda3\lib\site-packages\scipy\io\matlab\mio5.py", lin
e 590, in write_top
    self.write(arr)
  File "C:\ProgramData\Anaconda3\lib\site-packages\scipy\io\matlab\mio5.py", lin
e 619, in write
    self.write_struct(narr)
  File "C:\ProgramData\Anaconda3\lib\site-packages\scipy\io\matlab\mio5.py", lin
e 738, in write_struct
    self._write_items(arr)
  File "C:\ProgramData\Anaconda3\lib\site-packages\scipy\io\matlab\mio5.py", lin
e 755, in _write_items
    self.write(el[f])
  File "C:\ProgramData\Anaconda3\lib\site-packages\scipy\io\matlab\mio5.py", lin
e 611, in write
    % (arr, type(arr)))
TypeError: Could not convert None (type <class 'NoneType'>) to array

**Comment by LiuDaveLiu** [comment]
Gixed in 661cb0d219665ec454606f5f2b629bc621d7cc28
