### ISSUE TITLE
Issues getting facemap to run

### ISSUE THREAD

**Issue by Ndougly** [MouseLand/facemap#37]
Hi,

I've been trying to run facemap, but I've run into the same error each time, on multiple computers. Wondering if you could help out? Thank you!

Traceback (most recent call last):
File "C:\ProgramData\Anaconda3\envs\facemap\lib\runpy.py", line 193, in _run_module_as_main                               "__main__", mod_spec) 
File "C:\ProgramData\Anaconda3\envs\facemap\lib\runpy.py", line 85, in _run_code                                          exec(code, run_globals)
File "E:\David\Programs\facemap\facemap\__main__.py", line 39, in <module>                                                gui.run(moviefile, savedir)
File "E:\David\Programs\facemap\facemap\gui.py", line 1047, in run                                                        GUI = MainW(moviefile,savedir)
File "E:\David\Programs\facemap\facemap\gui.py", line 148, in __init__                                                    self.DLC_scatterplot.sigHovered.connect(self.DLC_points_hovered)                                                    AttributeError: 'ScatterPlotItem' object has no attribute 'sigHovered'

**Comment by Atika-Syeda** [comment]
Hey,
Please use `pip list` to check if you have the right version for the following and update accordingly:
PyQt5                  5.15.4
pyqtgraph              0.12.0

**Comment by Ndougly** [comment]
Thanks a lot for the very fast answer Will do that! 

-- 
KOURDOUGLI Nazim, PhD.
