### ISSUE TITLE
Error when using --movies on the command line

### ISSUE THREAD

**Issue by mwshinn** [MouseLand/facemap#41]
Hello,

I receive an error when using the example in the readme for opening with a movie specified.  This can be reproduced with the given example, i.e.,:

`python -m facemap --movie '/home/carsen/movie.avi' --savedir '/media/carsen/SSD/'`

The error is:

```
QGridLayoutEngine::addItem: Cell (0, 1) already taken
Traceback (most recent call last):
  File "/opt/miniconda3/envs/facemap/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/miniconda3/envs/facemap/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/miniconda3/envs/facemap/lib/python3.7/site-packages/facemap-0.2.0-py3.7.egg/facemap/__main__.py", line 39, in <module>
    gui.run(moviefile, savedir)
  File "/opt/miniconda3/envs/facemap/lib/python3.7/site-packages/facemap-0.2.0-py3.7.egg/facemap/gui.py", line 1047, in run
    GUI = MainW(moviefile,savedir)
  File "/opt/miniconda3/envs/facemap/lib/python3.7/site-packages/facemap-0.2.0-py3.7.egg/facemap/gui.py", line 174, in __init__
    self.load_movies([[moviefile]])
AttributeError: 'MainW' object has no attribute 'load_movies'
```

This error occurs both on the latest version 0e8fa78ee7f2c48cc73221ff9f3cfbec43d88957 and on the version from pypi.

Thank you!

UPDATE: Typo in the title, should be "--movie"

**Comment by Atika-Syeda** [comment]
thanks for the suggestion. It will be updated in the next release soon.
