### ISSUE TITLE
problem with install of new tracking version

### ISSUE THREAD

**Issue by hjwq** [MouseLand/facemap#45]
hi~ I tried to install the new tracking version, but some error came

the code shows up like this, hope you guys know how to deal with~ thank you!

(facemap) C:\Users\25230>pip install git+https://github.com/mouseland/facemap.git
Collecting git+https://github.com/mouseland/facemap.git
  Cloning https://github.com/mouseland/facemap.git to c:\users\25230\appdata\local\temp\pip-req-build-e8e_ylbm
  Running command git clone --filter=blob:none --quiet https://github.com/mouseland/facemap.git 'C:\Users\25230\AppData\Local\Temp\pip-req-build-e8e_ylbm'
  Resolved https://github.com/mouseland/facemap.git to commit 5011e1550acb1dd751bd7b5ec968531eefec0ea0
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\25230\AppData\Local\Temp\pip-req-build-e8e_ylbm\setup.py", line 39
          include_package_data=True,
                             ^
      SyntaxError: invalid syntax
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by hjwq** [comment]
![image](https://user-images.githubusercontent.com/100213882/159130734-d1cdba11-e9ce-40e7-92bd-4d201be4fe4f.png)

**Comment by hjwq** [comment]
I install it successfully, but whan I open it, with `python -m facemap`, it was still old verison? I ran it with my win10 laptop, some thing still wrong there? or it just could't work in win10
