### ISSUE TITLE
TypeError when selecting corneal reflection ROI

### ISSUE THREAD

**Issue by pulkitgoyal56** [MouseLand/facemap#54]
Hi, thanks for creating this incredibly useful software. We successfully installed a previous version but are experiencing some problems with the latest. Could you please orient us towards the fixes to these problems.

We have two issues, 

1. When selecting the ROI for corneal reflection, the following error output can be seen.

```
(facemap) C:\Users\_____\facemap>python -m facemap
C:\Users\_____\anaconda3\envs\facemap\lib\site-packages\torch\_masked\__init__.py:223: UserWarning: Failed to initialize NumPy: module compiled against API version 0xf but this version of numpy is 0xe (Triggered internally at  ..\torch\csrc\utils\tensor_numpy.cpp:68.)
  example_input = torch.tensor([[-3, -2, -1], [0, 1, 2]])
numpy version: 1.21.6
python version: 3.10.4
Global varaibles set:
N_FACTOR: 4
SIGMA: 3.0
Running Facemap GUI w/ pose tracker
QGridLayoutEngine::addItem: Cell (0, 1) already taken
QGraphicsScene::removeItem: item 0x21036637210's scene (0x0) is different from this scene (0x210363257a0)
QGraphicsScene::removeItem: item 0x21034d9d620's scene (0x0) is different from this scene (0x210363257a0)
Traceback (most recent call last):
  File "C:\Users\______\facemap\facemap\roi.py", line 47, in <lambda>
    self.ROI.sigRegionChangeFinished.connect(lambda: self.position(parent))
  File "C:\Users\______\facemap\facemap\roi.py", line 106, in position
    parent.sl[1].setValue(parent.saturation[self.iROI] * 100 / 255)
TypeError: setValue(self, int): argument 1 has unexpected type 'float'
Traceback (most recent call last):
  File "C:\Users\______\facemap\facemap\roi.py", line 47, in <lambda>
    self.ROI.sigRegionChangeFinished.connect(lambda: self.position(parent))
  File "C:\Users\______\facemap\facemap\roi.py", line 106, in position
    parent.sl[1].setValue(parent.saturation[self.iROI] * 100 / 255)
TypeError: setValue(self, int): argument 1 has unexpected type 'float'
```

2. Nothing happens when the `process` button is clicked. No log output, no results.

Thanks a lot!

**Comment by pulkitgoyal56** [comment]
The problem was fixed by using Python 3.9 instead of Python 3.6.
