### ISSUE TITLE
Macbook M1 issue with pyqt5 and subsequent software launch

### ISSUE THREAD

**Issue by jlm2303** [MouseLand/facemap#96]
### Describe the issue:

Hello,

I tried to install facemap on my Macbook Pro with an M1 chip and followed the instructions provided on github.
PyQt5 doesn't seem to be compatible with new Macbooks, hence I installed PyQt6 which seems to work smoothly.
However, to run facemap successfully on Mac PyQt5 is necessary because it imports specific features that are only called from PyQt5 and not PyQt6.

I tried multiple ways of installing PyQt5, from homebrew to creating an additional environment, but it seems not possible to make it run on Mac. I'd appreciate any help or suggestions a lot.

Many thanks in advance.

### Provide environment info:

     active environment : facemap
    active env location : /Users/johanna/anaconda3/envs/facemap
            shell level : 2
       user config file : /Users/johanna/.condarc
 populated config files : /Users/johanna/.condarc
          conda version : 23.1.0
    conda-build version : 3.23.3
         python version : 3.10.9.final.0
       virtual packages : __archspec=1=arm64
                          __osx=13.3=0
                          __unix=0=0
       base environment : /Users/johanna/anaconda3  (writable)
      conda av data dir : /Users/johanna/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-arm64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-arm64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/johanna/anaconda3/pkgs
                          /Users/johanna/.conda/pkgs
       envs directories : /Users/johanna/anaconda3/envs
                          /Users/johanna/.conda/envs
               platform : osx-arm64
             user-agent : conda/23.1.0 requests/2.28.1 CPython/3.10.9 Darwin/22.4.0 OSX/13.3
                UID:GID : 501:20
             netrc file : None
           offline mode : False

### Error message:

```shell
(facemap) johanna@Johannas-MacBook-Pro ~ % python -m facemap
Traceback (most recent call last):
  File "/Users/johanna/anaconda3/envs/facemap/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/johanna/anaconda3/envs/facemap/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/johanna/anaconda3/envs/facemap/lib/python3.8/site-packages/facemap/__main__.py", line 7, in <module>
    from facemap import process
  File "/Users/johanna/anaconda3/envs/facemap/lib/python3.8/site-packages/facemap/process.py", line 10, in <module>
    from facemap import pupil, running, utils
  File "/Users/johanna/anaconda3/envs/facemap/lib/python3.8/site-packages/facemap/utils.py", line 9, in <module>
    from facemap.pose import refine_pose
  File "/Users/johanna/anaconda3/envs/facemap/lib/python3.8/site-packages/facemap/pose/refine_pose.py", line 7, in <module>
    import pyqtgraph as pg
  File "/Users/johanna/anaconda3/envs/facemap/lib/python3.8/site-packages/pyqtgraph/__init__.py", line 18, in <module>
    from .colors import palette
  File "/Users/johanna/anaconda3/envs/facemap/lib/python3.8/site-packages/pyqtgraph/colors/palette.py", line 1, in <module>
    from ..Qt import QtGui
  File "/Users/johanna/anaconda3/envs/facemap/lib/python3.8/site-packages/pyqtgraph/Qt/__init__.py", line 54, in <module>
    raise Exception("PyQtGraph requires one of PyQt5, PyQt6, PySide2 or PySide6; none of these packages could be imported.")
Exception: PyQtGraph requires one of PyQt5, PyQt6, PySide2 or PySide6; none of these packages could be imported.
(facemap) johanna@Johannas-MacBook-Pro ~ % pip install pyqt5
Collecting pyqt5
  Using cached PyQt5-5.15.9.tar.gz (3.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      Querying qmake about your Qt installation...
      Traceback (most recent call last):
        File "/Users/johanna/anaconda3/envs/facemap/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/johanna/anaconda3/envs/facemap/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/johanna/anaconda3/envs/facemap/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "/private/var/folders/zw/v119x0wx0_jb68mdv179_sgw0000gn/T/pip-build-env-4w7c5nh3/overlay/lib/python3.8/site-packages/sipbuild/api.py", line 46, in build_wheel
          project = AbstractProject.bootstrap('wheel',
        File "/private/var/folders/zw/v119x0wx0_jb68mdv179_sgw0000gn/T/pip-build-env-4w7c5nh3/overlay/lib/python3.8/site-packages/sipbuild/abstract_project.py", line 87, in bootstrap
          project.setup(pyproject, tool, tool_description)
        File "/private/var/folders/zw/v119x0wx0_jb68mdv179_sgw0000gn/T/pip-build-env-4w7c5nh3/overlay/lib/python3.8/site-packages/sipbuild/project.py", line 601, in setup
          self.update(tool)
        File "project.py", line 165, in update
      sipbuild.exceptions.UserException
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by inchinn1** [comment]
I had the same issue, it is just that pip's pyqt5 does not work on arm64 architectures. You can get it working by using 'conda install pyqt', conda's version support arm64 and worked with my M2 chip

**Comment by Atika-Syeda** [comment]
thanks for the help @inchinn1

**Comment by Atika-Syeda** [comment]
Hi @jlm2303 we have not yet tested facemap on Macbook M1/M2 but hope to update it in the future. It currently only supports Windows, Linux and Apple intel machines.
